config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'projects/:project_id/billing', :to => 'billing#index'
get 'projects/:project_id/invoice', :to => 'invoice#index'



app/controllers/billing_controller.rb
class BillingController < ApplicationController
  unloadable
  before_filter :find_project, :authorize, :only => :index

  accept_api_auth :index

  GROUP_NAMES = ["CAN_SEE_PROFITS_CHARTS", "CAN_SEE_BILLING_CHARTS"]

  def index

    if params[:base_date] != nil
      base_date = Date.strptime(params[:base_date], "%Y-%m-%d") rescue nil
      @context = Context.new(base_date, true, params[:debug].present?)
    else
      @context = Context.new(Date.today, false, params[:debug].present?)
    end

    if params[:print] != nil
      @context.print = true if params[:print] == "true"
    end

    begin
      authorization_check

      @data = DataAccessor.new(params[:project_id], @context)

      move_foward = @data.setup

      # In case of not bottom layer project
      return unless move_foward

      @data.grab_data

      if @data.fusion_project.tm?
        if @data.fusion_project.location == FsgProject::LOCATION_LA and @data.fusion_project.weekly_invoiced?
          @billing = WeeklyTmContractHoursSowCalculator.new(@data, @context)
        else
          @billing = MonthlyTmContractHoursSowCalculator.new(@data, @context)
        end
      elsif @data.fusion_project.tm_simple?
        if @data.fusion_project.location == FsgProject::LOCATION_LA and @data.fusion_project.weekly_invoiced?
          @billing = WeeklyTmSimpleSowCalculator.new(@data, @context)
        elsif @data.fusion_project.fusion_system_group
          @billing = MonthlyTmFsgSowCalculator.new(@data, @context)
        else
          @billing = MonthlyTmSimpleSowCalculator.new(@data, @context)
        end
      elsif @data.fusion_project.maintenance? and @data.fusion_project.location == FsgProject::LOCATION_TK
        @billing = MaintenanceSowCalculator.new(@data, @context)
      elsif @data.fusion_project.fixed? and @data.fusion_project.location == FsgProject::LOCATION_TK
        @billing = FixedSowCalculator.new(@data, @context)
      elsif @data.fusion_project.miscellaneous?
        @billing = MiscellaneousSowCalculator.new(@data, @context)
      else
        raise "No implementaion for %s and %s." % \
              [@data.fusion_project.type, @data.fusion_project.location]
      end

      @billing.setup
      @billing.calc

    rescue => e
      @context.set_error_happen
      @error = e.message
      @error += "\n" + e.backtrace.join("\n") if @context.debug_mode?
      return 0
    end



    respond_to do |format|
      format.html # index.html.erb
      format.csv  { send_data(report_to_csv(), :type => 'text/csv;', :filename => "billing_#{@data.fusion_project.identifier}.csv") }
#      format.pdf { send_data(:pdf => 'test', :type => 'application/pdf;', :encoding => 'UTF-8', :layout => 'invoice.html') }
#       format.pdf { send_data(:pdf => 'invoice', :type => 'application/pdf;', :orientation => 'Landscape', :encoding => 'UTF-8') }
      format.pdf do
        render :pdf => "invoice",
#               :orientation => 'Landscape',
               :template => 'invoice/_invoice.html.erb',
               :layout => 'invoice',
               :encoding    => 'UTF-8',
               :show_as_html => params[:debug].present?
      end

      format.json {
        # These calculations for monthly report only
        revenue = 0.0
        case @data.fusion_project.original_sow_type
        when "T&M" then
          if @data.fusion_project.custom_value["Pre-paid Until"] == nil
            revenue = @billing.get_last_collection.final_charge
          else
            revenue = @data.fusion_project.fixed_contractual_hourly_rate * @data.fusion_project.contractual_hours
          end
        when "Fixed" then
          revenue = @data.fusion_project.value_to_fusion / @data.fusion_project.get_term

        when "Client Site" then
          revenue = @data.fusion_project.value_to_fusion
        when "Manual" then
          revenue = @data.fusion_project.fixed_contractual_hourly_rate * @data.fusion_project.contractual_hours
        when "Maintenance" then
          revenue = @data.fusion_project.additional_service_fees
        end
        unless @data.fusion_project.fixed?

          render :json => {
            "project" => @data.fusion_project.name,
            "tracker" => @data.fusion_project.type,
            "last_rollover_hour" => @billing.get_last_collection.next_rollover_hours,
            "last_billable_hour" => @billing.get_last_collection.billable_total_hours,
            "start_date" => @billing.get_last_collection.beginning_date,
            "end_date" => @billing.get_last_collection.end_date,
            "revenue" => @billing.get_last_collection.final_charge
          }
        else
          render :json => {
            "project" => @data.fusion_project.name,
            "tracker" => @data.fusion_project.type,
            "start_date" => @data.fusion_project.project_start_date,
            "end_date" => @data.fusion_project.project_due_date,
            "revenue" => @data.fusion_project.value_to_fusion
          }

      end
      }
    end
  end

  private
  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def report_to_csv
    require 'fastercsv'
    csv_text = @billing.generate_csv() rescue FasterCSV.generate
    csv_text.to_s
  end

  def authorization_check(ok_group=GROUP_NAMES)
    flag = false
    User.current.groups.each do |group|
      if ok_group.include? group.name
        if group.name == "CAN_SEE_BILLING_CHARTS"
          @context.client_restrict = true
        end
        flag = true
      end
    end
    raise "You don't have a permission to access this page. " unless flag
  end
end

# gedit billing/app/controllers/billing_controller.rb billing/app/views/billing/* billing/lib/* &


app/helpers/billing_helper.rb
module BillingHelper
  def summary_table_maintenance(project, collection, context)
    buff = ""
    buff << "<table border=\"0\" >"
    buff << "  <tr>"
    buff << "    <td>Contract Name </td><td>%s</td>"%[project.name]
    buff << "  </tr><tr>"
    buff << "    <td>Beginning Date </td><td>%s</td>"%[collection.beginning_date]
    buff << "  </tr><tr>"
    buff << "    <td>End Date </td><td>%s</td>"%[collection.end_date]
    buff << "  </tr><tr>"
    buff << "    <td width=\"250\" >Total Hours</td><td width=\"630\">%s Hours</td>"%
                     [collection.total_hours]

    buff << "  </tr><tr>"
    buff << "    <td>Charge </td><td>%s</td>"%[collection.final_charge]
    buff << "  </tr>"
    buff << "</table>"
    buff.html_safe
  end

  def summary_table_miscellaneous(project, collection, context)
    buff = ""
    buff << "<table border=\"0\" >"
    buff << "  <tr>"
    buff << "    <td>Contract Name </td><td>%s</td>"%[project.name]
    buff << "  </tr><tr>"
    buff << "    <td>Beginning Date </td><td>%s</td>"%[collection.beginning_date]
    buff << "  </tr><tr>"
    buff << "    <td>End Date </td><td>%s</td>"%[collection.end_date]
    buff << "  </tr><tr>"
    buff << "    <td width=\"250\" >Total Hours</td><td width=\"630\">%s Hours</td>"%
                     [collection.total_hours]

    buff << "  </tr><tr>"
    buff << "    <td>Accumulated Charges </td><td>%s</td>"%[collection.final_charge]
    buff << "  </tr>"
    buff << "</table>"
    buff.html_safe
  end
  
  def summary_table_fixed(project, billing, context)
    buff = ""
    buff << "<table border=\"0\" >"
    buff << "  <tr>"
    buff << "    <td>Contract Name </td><td>%s</td>"%[project.name]
    buff << "  </tr><tr>"
    buff << "    <td>Beginning Date </td><td>%s</td>"%[project.project_start_date]
    buff << "  </tr><tr>"
    buff << "    <td>End Date </td><td>%s</td>"%[project.project_due_date]
    buff << "  </tr><tr>"
    buff << "    <td width=\"250\" >Total Hours</td><td width=\"630\">%s Hours</td>"%
                     [billing.project_total_hours]

    buff << "  </tr><tr>"
    buff << "    <td>Charge</td><td>%s</td>"%  
                     [project.value_to_fusion]
    buff << "  </tr>"
    buff << "</table>"
    buff.html_safe
  end
  
  
  def summary_table(project, collection, context)
    buff = ""
    buff << "<table border=\"0\" >"
    buff << "  <tr>"
    buff << "    <td>Contract Name </td><td>%s</td>"%[project.name]
    buff << "  </tr><tr>"
    buff << "    <td>Beginning Date </td><td>%s</td>"%[collection.beginning_date]
    buff << "  </tr><tr>"
    buff << "    <td>End Date </td><td>%s</td>"%[collection.end_date]
    buff << "  </tr><tr>"
    buff << "    <td width=\"250\" >Total Hours</td><td width=\"630\">%s Hours</td>"%
                     [collection.total_hours]

    buff << "  </tr><tr>"
    buff << "    <td>Billable Hours </td><td>%s Hours</td>"%  
                     [collection.billable_total_hours]
    buff << "  </tr><tr>"
    buff << "    <td> - Standard Hours </td><td>%s Hours</td>"%  
                     [collection.standard_hours]
    buff << "  </tr><tr>"
    buff << "    <td> - Non-Standard Hours </td><td>%s Hours</td>"%  
                     [collection.nonstandard_hours]
    
    unless context.client_restrict
      buff << "  </tr><tr>"
      buff << "    <td>Non-Billable Hours </td><td>%s Hours</td>"%  
                     [collection.nonbillable_total_hours]
    end
    
    unless project.tm_simple? or project.miscellaneous?
    buff << "  </tr><tr>"
    buff << "    <td>Contractual Hours </td><td>%s Hours</td>"%
                     [project.contractual_hours]
    buff << "  </tr><tr>"
    buff << "    <td>Rollover Hours </td><td>%s Hours</td>"%
                     [collection.rollover_hours]
    buff << "  </tr><tr>"
    buff << "    <td>Contractual and Rollover Hours </td><td>%s Hours</td>"%
                     [collection.contractual_and_rollover_hours]
    
    buff << "  </tr><tr>"
    buff << "    <td>Remaining Hours </td><td>%s Hours</td>"%  
                     [collection.remaining_hours]
    end
    
    unless context.client_restrict
      buff << "  </tr><tr>"
      buff << "    <td>Billable Ratio </td><td>%s %s</td>"% 
                     [collection.billable_ratio, '%']
      buff << "  </tr><tr>"
      buff << "    <td>Non Billable Ratio </td><td>%s %s</td>"%  
                     [collection.nonbillable_ratio, '%']
    end
    
    unless context.client_restrict or project.tm_simple? or project.miscellaneous?
      buff << "  </tr><tr>"
      buff << "    <td>Cotractual Minimum Charge </td><td>%s</td>"%  
                     [collection.minimum_charge]
    end
    
    buff << "  </tr><tr>"
    buff << "    <td>Charge</td><td>%s</td>"%  
                     [to_number_with_delimiter(collection.final_charge, true)]
    
    unless context.client_restrict or project.tm_simple? or project.miscellaneous?
      message = collection.description.join("<br/>")
      buff << "  </tr><tr>"
      buff << "    <td>Details</td><td>%s</td>"%  
                     [message]
    end
    
    buff << "  </tr>"
    buff << "</table>"
    buff.html_safe
  end
  
  def tm_contract_header(project, collection)
    buff = ""
    buff << "<table border=\"0\">"
    buff << "  <tr>"
    buff << "    <td>Contract Name </td><td>%s</td>" % [project.name]
    buff << "  </tr><tr>"
    buff << "    <td>Beginning Date </td><td>%s</td>" % [collection.beginning_date]
    buff << "  </tr><tr>"
    buff << "    <td>End Date </td><td>%s</td>" % [collection.end_date]

    buff << "  </tr><tr>"
    buff << "    <td>Contractual Hours </td><td>%f</td>" % [project.contractual_hours]
    buff << "  </tr><tr>"
    buff << "    <td>Fixed Contractual Hourly Rate </td><td>%f</td>" %
      [project.fixed_contractual_hourly_rate]
    buff << "  </tr><tr>"
    buff << "    <td>Location </td><td>%s</td>" % [project.location]
    
    collection.billable_stock.each_key do |key|
      buff << "  </tr><tr>"
      buff << "    <td>Rate %s </td><td>%s</td>" % [key, project.custom_value[key]]
    end
    
    buff << "  </tr><tr>"
    buff << "  </tr>"
    buff << "</table>"
    buff.html_safe
  end
  
  
  def transaction_table(collection, billable_option=true)
    buff = ""
    counter = 0
    
    coler_changer = true
    buff << "<table width=\"878\" border=\"0\" cellspacing=\"1\" bgcolor=\"black\">"
    buff << "<tr>"
    buff << "<th bgcolor=\"gray\" width=\"80\" ><font color=\"#ffffff\">Date</font></td>"
    buff << "<th bgcolor=\"gray\" width=\"120\"><font color=\"#ffffff\">In Charge</font></th>"
    buff << "<th bgcolor=\"gray\" width=\"100\"><font color=\"#ffffff\">Tracker</font></th>"
    buff << "<th bgcolor=\"gray\" width=\"150\"><font color=\"#ffffff\">Activity</font></th>"
    buff << "<th bgcolor=\"gray\"              ><font color=\"#ffffff\">Comments</font></th>"
    buff << "<th bgcolor=\"gray\" width=\"30\"><font color=\"#ffffff\">Hours</font></th>"
    buff << "</tr>"
    
    collection.sort.each do |time_entry|
    
      if time_entry.billable? == billable_option
        counter += 1
        if coler_changer
          buff << '<tr bgcolor="#F0F0F0">' 
          coler_changer = false
        else
          buff << '<tr bgcolor="white">' 
          coler_changer = true
        end
        link = "<a href=\"../../time_entries/#{time_entry.id.to_s}/edit\" data-method=\"get\">#{time_entry.hours.to_s}</a>"
          
        buff << "<td align=\"center\" >%s</td>"%[time_entry.spent_on.strftime("%d %b %Y")]
        buff << "<td  align=\"center\" >%s</td>"%[time_entry.user_name.gsub(".", " ").titleize]
        buff << "<td  align=\"center\" >%s</td>"%[time_entry.tracker]
        buff << "<td >%s</td>"%[time_entry.activity]
        buff << "<td >%s</td>"%[time_entry.comments]
        buff << "<td align=\"right\">%s</td>"%[link]
        buff << "</tr>"
      end
    end  
    buff << "</table>"
    return counter > 0 ? buff.html_safe : "No Activity"
  end
  
  def to_number_with_delimiter(number, roundup=false)
    return number if number.kind_of? String
    number = number.round if roundup
    minus = false
    if number < 0
      number = number * -1
      minus = true
    end
    first, last = number.to_s.split(".")
    str_number = ""
    if last != nil
      str_number = first.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse + "." + last
    else
      str_number = first.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse
    end
    str_number = "-#{str_number}" if minus
    str_number
  end
end


app/views/billing/_debug.html.erb
<h3>Debug</h3>
<% @context.debug.each do |message| %>
  <%= message %></br>
<% end %>

app/views/billing/_error.html.erb
<h3>Error</h3>
Sorry. <br/>
<pre>
  <%= @error %>
</pre>

app/views/billing/_fixed.html.erb
<h3>Real-time</h3>

<ul>
  <li>
    <h4>Summary</h4>
  </li>
  <%= summary_table_fixed(@data.fusion_project, @billing, @context) %>
  <br/><br/>
  
  <% @billing.collection_hash.sort.each do |key, collection| %>
    <li>
      <h4><%= key.strftime("%b %Y") %></h4>
    </li>
    <%= transaction_table collection %>
    <br/><br/>
  <% end %>
</ul>

app/views/billing/_lastmonth.html.erb
<h3>Last Month</h3>
<% last_month_key = Date.today.change(:day => 1) << 1 %>


  <% collection = @billing.collection_hash[last_month_key] %>
  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table(@data.fusion_project, collection, @context) %>
    <li>
      <h4>Billable Transactions</h4>
    </li>


<% if false %>
    <% link_csv = "./billing.csv?base_date=" + last_month_key.strftime("%Y-%m-%d") %>
<% end %>

    <% link_csv = "./billing.csv?base_date=" + @context.base_date.change(:day => 1).strftime("%Y-%m-%d") %>

    <%= link_to("CSV Download", link_csv, :method => :get) %>

    <%= transaction_table collection %>
    <% unless @context.client_restrict %>
      <li>
        <h4>Non-Billable Transactions</h4>
      </li>
      <%= transaction_table collection, false %>
    <% end %>
  </ul>

<% if false %>
<% if @billing.collection_hash.key? last_month_key and @billing.collection_hash[last_month_key].charge.valid? %>
<% else %>
  No Data Found
<% end %>
<% end %>

app/views/billing/_lastweek.html.erb
<h3>Last Week</h3>
<% today = Date.today %>
<% last_monday_key = today - (today.wday - 1) - 7 %>


  <% collection = @billing.collection_hash[last_monday_key] %>
  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table(@data.fusion_project, collection, @context) %>
    <li>
      <h4>Billable Transactions</h4>
    </li>
    <% link_csv = "./billing.csv?base_date=" + last_monday_key.strftime("%Y-%m-%d") %>
    <%= link_to("CSV Download", link_csv, :method => :get) %>
    <br/>
    <%= transaction_table collection %>
    <% unless @context.client_restrict %>
      <li>
        <h4>Non-Billable Transactions</h4>
      </li>
      <%= transaction_table collection, false %>
    <% end %>
  </ul>

app/views/billing/_maintenance.html.erb
<h3>Last Month</h3>
<% last_month_key = Date.today.change(:day => 1) << 1 %>
<% collection = @billing.get_last_collection %>

  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table_maintenance(@data.fusion_project, collection, @context) %>

    <% unless @context.client_restrict %>
      <li>
        <h4>Activities</h4>
      </li>
      <%= transaction_table collection %>
    <% end %>

  </ul>

<h3>This Month</h3>
<% collection = @billing.get_this_collection %>

  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table_maintenance(@data.fusion_project, collection, @context) %>

    <% unless @context.client_restrict %>
      <li>
        <h4>Activities</h4>
      </li>
      <%= transaction_table collection %>
    <% end %>

  </ul>



<% if false %>
<% if @billing.collection_hash.key? last_month_key and @billing.collection_hash[last_month_key].size > 0 %>
  <% collection = @billing.collection_hash[last_month_key] %>
  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table(@data.fusion_project, collection, @context) %>
    <li>
      <h4>Billable Transactions</h4>
    </li>
    <% link_csv = "./billing.csv?base_date=" + last_month_key.strftime("%Y-%m-%d") %>
    <%= link_to("CSV Download", link_csv, :method => :get) %>
    <%= transaction_table collection %>
    <% unless @context.client_restrict %>
      <li>
        <h4>Non-Billable Transactions</h4>
      </li>
      <%= transaction_table collection, false %>
    <% end %>
  </ul>
<% else %>
  No Data Found
<% end %>

<% end %>

app/views/billing/_notbottomproject.html.erb
<h3>Select a project</h3>
<% @data.fusion_projects.each do |project| %>
  <a href="<%= raw(project.uri_charts) %>" data-method="get"><%= project.name %></a><br/>
<% end %>

app/views/billing/_thismonth.html.erb
<h3>This Month</h3>
<% this_month_key = Date.today.change(:day => 1) %>

  <% collection = @billing.collection_hash[this_month_key] %>
  <ul>
    <li>
      <h4>Summary</h4>
    </li>
      <%= summary_table(@data.fusion_project, collection, @context) %>
    <li>
      <h4>Billable Transactions</h4>
    </li>
    <%= transaction_table collection %>
    <% unless @context.client_restrict %>
      <li>
        <h4>Non-Billable Transactions</h4>
      </li>
      <%= transaction_table collection, false %>
    <% end %>
  </ul>

app/views/billing/_thisweek.html.erb
<h3>This Week</h3>
<% this_day = Date.today %>
<% this_monday_key = this_day - (this_day.wday - 1) %>


  <% collection = @billing.collection_hash[this_monday_key] %>
  <ul>
    <li>
      <h4>Summary</h4>
    </li>
    <%= summary_table(@data.fusion_project, collection, @context) %>
    <li>
      <h4>Billable Transactions</h4>
    </li>
    <%= transaction_table collection %>
    <% unless @context.client_restrict %>
      <li>
        <h4>Non-Billable Transactions</h4>
      </li>
      <%= transaction_table collection, false %>
    <% end %>
  </ul>

app/views/billing/_view_issues_show_description_bottom.html.erb
<% project = Project.where(name: issue.subject[0...-10]).first %>
<% base_date = Date.new(Date.today.year, Date.today.month, 1) %>
<% if project %>
  <ul>
    <li><%= link_to 'Billing', project_path(project) + '/billing' %></li>
    <li><%= link_to 'Invoice', project_path(project) + '/invoice' %></li>
    <li><%= link_to 'CSV Download', project_path(project) + "/billing.csv?base_date=#{base_date}" %></li>
  </ul>
<% end %>

app/views/billing/index.html.erb
<h2>Billing</h2>

<% if @context.base_date_spacify? and @context.base_date.month != Date.today.month %>
  <table border="0" cellspacing="1" cellpadding="2" bgcolor="#ff00ff">
    <tr>
      <td align="center">
      <font color="#FFFFFF" style="font-size:13px">
        Show as of <%= @context.base_date.strftime("%d %b %Y") %>. 
        <%= link_to("Change to the current data", "./billing", :method => :get) %>
      </font>
      </td>
    </tr>
  </table>
  <br/>
<% end %>

<% if @context.output_type == :not_bottom_project %>
  <div id="project_links">
    <%=render :partial =>'notbottomproject' %>
  </div>
<% elsif @context.output_type == :error_occured %>
  <div id="error">
    <%=render :partial =>'error' %>
  </div>
<% else %>

  <% if @context.warning.size > 0 %>
    <div style="width: 880px; border-style: solid ; border-width: 1px; border-color: #ff0000">
      <% @context.warning.each do |warning| %>
        <b><font color="#ff0000">[Warning] <%= warning %></font></b><br/>
      <% end %>
    </div>
    <br/>
  <% end %>

  <% if @data.fusion_project.tm? or @data.fusion_project.tm_simple? or @data.fusion_project.miscellaneous? %>
    <% if @data.fusion_project.location == FsgProject::LOCATION_LA and @data.fusion_project.weekly_invoiced? %>
      <div id="last_week">
        <%=render :partial =>'lastweek' %>
      </div>
      <div id="this_week">
        <%=render :partial =>'thisweek' %>
      </div>
    <% else %>
      <div id="last_month">
        <%=render :partial =>'lastmonth' %>
      </div>
      <div id="this_month">
        <%=render :partial =>'thismonth' %>
      </div>
    <% end %>
  <% elsif @data.fusion_project.maintenance? %>
    <div id="maintenance">
      <%=render :partial =>'maintenance' %>
    </div>
  <% elsif @data.fusion_project.fixed? %>
    <div id="fixed">
      <%=render :partial =>'fixed' %>
    </div>
  <% end %>

<% end %>


</br>
</br>

<% if @context.debug_mode? %>
  <div id="debug">
    <%=render :partial =>'debug' %>
  </div>
<% end %>
